### ISSUE TITLE
No support for deeply nested dictionaries?

### ISSUE THREAD

**Issue by joncol** [tonsky/tongue#17]
Hi, thanks for the nice library.

There seems to be some problem with dictionaries with deeper nesting levels.

I tried with the following dictionary:
```clojure
{:en {:animals {:dog "Dog"                      ;; => :animals/dog
                :cat "Cat"                      ;; => :animals/cat
                :flying {:bird "Bird"           ;; => "Missing key"
                         :dinosaur "Dinosaur"}} ;; => "Missing key"
```
The `flying` keys are not found when trying to reference them as `:animals.flying/bird`, or `:animals/flying.bird` for instance.

`:cat` and `:dog` (which are only 1 nesting-level deep) work fine of course.

Is this something you would consider adding support for?

**Comment by tonsky** [comment]
There will be under `:animals.flying/bird` etc. Last segment catenated using `/`, rest using `.`

**Comment by joncol** [comment]
I tried this, but it gave the same error message. I have a minimal failing example at https://bitbucket.org/joncol/tongue-play if you'd like to have a look.

**Comment by tonsky** [comment]
You are correct, those are simply not supported. I’d love to add support for them though

**Comment by valerauko** [comment]
@tonsky I put up a PR with the behavior described above working. Hope it's all right
