### ISSUE TITLE
Namespaced keys don't work anymore

### ISSUE THREAD

**Issue by JoelSanchez** [tonsky/tongue#19]
Any keyword with a namespace gets its namespace removed :|

```
(tongue.core/build-dict {:a/b "hello"})
=> {:b "hello"}
```

**Comment by tonsky** [comment]
I don’t remember whether it was intentional or not :) probably not. Care to provide a PR?

**Comment by JoelSanchez** [comment]
I'll provide a PR, I believe it wasn't intentional because of the README:
```
 ;; namespaced keys
          :weather/rain   "Rain"
          :weather/clouds "Clouds"
```
