### ISSUE TITLE
it's not compatible with 1.9

### ISSUE THREAD

**Issue by geraldodev** [tonsky/tongue#3]
Hi,

In order to use tongue with 1.9.0 alpha-10 we import it as:
                 [tongue "0.1.4" :exclusions [clojure-future-spec]]

That solves lein repl compilation problem.

The  problem is inst.cljc and core.cljc which refers clojure-future-spec. That comes already with clojure right ? Since it's not being monkey patched and it's formally called we need to remove from core and inst.

Regards,

geraldodev, a happy datascript user.

**Comment by tonsky** [comment]
I decided to just drop clojure-future-spec completely and require 1.9 from 0.2.0 forward. If I'd need to add anything I'll just backport it to 0.1.* branch before Clojure 1.9 finally releases.
