### ISSUE TITLE
Suggestion: aliases

### ISSUE THREAD

**Issue by cjohansen** [tonsky/tongue#8]
I find it useful to use specific keys for most things in my UI, even when strings are the same. I do not, however, enjoy repeating the same strings all over. An example would be a "confirm button". I typically want this to be the same text most places, but I still want to use specific keys in specific views (`:cart/confirm-button`, `:profile/save-button`) so I can easily update texts without updating views.

To do this, I've implemented a transform for my dictionaries where values can be keywords, effectively making them aliases:

```
{:button/confirm "OK"
 :cart/confirm-button :button/confirm
 :profile/save-button :button/confirm}
```

Would you be interested in a pull request that made this a Tongue feature?

**Comment by tonsky** [comment]
Sounds like a good idea! Seems like it shouldn’t break anything. I’ll happily review a PR
